#!/bin/bash

PARDIR=$LABDIR/read/$1
cd ${PARDIR}
RAW=Raw
mkdir DTI EDF E-Prime EV EV2 Fieldmap Func Physio Rest Struct fMRI_Analyses
dcm2nii $RAW
mv Raw/*.nii.gz $PARDIR/
mv Raw/*.bvec $PARDIR/
mv Raw/*.bval $PARDIR/
mv *mprnssag* Struct/
mv *Run* Func/
mv *ddiff* DTI/
mv *rest* Rest/
mv *SpinEcho* Fieldmap/
mkdir EDF/Run1 EDF/Run2 EDF/Run3 EDF/Run4 EDF/Run5 EDF/Extra
mkdir E-Prime/Run1 E-Prime/Run2 E-Prime/Run3 E-Prime/Run4 E-Prime/Run5 E-Prime/Extra
mkdir EV/Run1 EV/Run2 EV/Run3 EV/Run4 EV/Run5
mkdir EV2
mkdir EV2/Run1 EV2/Run2 EV2/Run3 EV2/Run4 EV2/Run5
cd Func
mkdir Refs
for line in $(du -hs * | grep K)
do
	if [ "${line:3}" != 'K' ];	then
		if [ "${line:0:4}" != 'Refs' ];	then
			mv $line Refs/
		fi
	fi
done

for line in $(ls | grep .nii.gz)
do
	dir=${line:23:4}
	mkdir $dir
	mv $line $dir/
done
cd $PARDIR
chmod 550 Raw
